# Generated by Django 4.1.5 on 2023-02-04 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fcha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'trabajador',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('estado', models.IntegerField()),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioApp.trabajador')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
